name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -f serving/Dockerfile -t ctr-prediction-api .

      - name: Run container
        run: docker run -d -p 8000:8000 --name ctr-api ctr-prediction-api

      - name: Wait for app to start
        run: sleep 5

      - name: Test health endpoint
        run: curl -s http://localhost:8000/health

      - name: Test predict endpoint
      - run: |
          EXAMPLE_FEATURE_VALUES='{
            "C1": 1005,
            "banner_pos": 0,
            "device_type": 1,
            "device_conn_type": 0,
            "C14": 15706,
            "C15": 320,
            "C16": 50,
            "C17": 1722,
            "C18": 0,
            "C19": 35,
            "C20": -1,
            "C21": 79,
            "hour_of_day": 14,
            "day_of_week": 1,
            "site_id": "1fbe01fe",
            "site_domain": "f3845767",
            "site_category": "28905ebd",
            "app_id": "ecad2386",
            "app_domain": "7801e8d9",
            "app_category": "07d7df22",
            "device_model": "44956a24",
            "is_weekend": false,
            "is_app": false
          }'

          URL="http://localhost:8000/predict"
          HEADER="Content-Type: application/json"

          curl -X POST $URL -H "$HEADER" -d "$EXAMPLE_FEATURE_VALUES"

      - name: Stop container
        run: docker stop ctr-api
